name: commons_core
description: A Core Module containing all basics abstractions and utils classes

version: 1.0.0

environment:
  sdk: "3.5.4"

dependencies:
  flutter:
    sdk: flutter
  meta: 1.15.0
  equatable: 2.0.5
  package_info_plus: 8.1.1
  lottie: 3.1.3
  collection: ^1.17.0
  dio: 5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
