name: commons_media_validation
description: A Midia Validation Module containing all flow to email and sms validation

version: 1.0.0

environment:
  sdk: "3.5.4"

dependencies:
  flutter:
    sdk: flutter
  commons_core:
    path: ../core
  commons_crash_report:
    path: ../crash_report

  equatable: ^2.0.5
  flutter_bloc: 8.1.2
  shimmer: 3.0.0
  injectable: 2.5.0
  get_it: 8.0.2
  dio: 5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  build_runner: 2.4.13
  injectable_generator: 2.6.2
