name: commons_crash_report
description: A Crash Report Module containing all basics abstractions to send crash report

version: 1.0.0

environment:
  sdk: "3.5.4"

dependencies:
  flutter:
    sdk: flutter
  commons_core:
    path: ../core

  firebase_core: 3.8.0
  firebase_crashlytics: 4.1.5
  injectable: 2.5.0
  get_it: 8.0.2
  equatable: 2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  build_runner: 2.4.13
  injectable_generator: 2.6.2
