name: commons_interceptors
description: A Core Inteceptors containing all Interceptors used on API Calls

version: 1.0.0

environment:
  sdk: "3.5.4"

dependencies:
  flutter:
    sdk: flutter
  dio: 5.7.0
  injectable: 2.5.0
  get_it: 8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  build_runner: 2.4.13
  injectable_generator: 2.6.2